volumes:
    mongo-data:
        external: true
services:
  mongo:
    image: mongo:6
    volumes:
        - ./setup/mongodb:/docker-entrypoint-initdb.d
        - mongo-data:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      CORS_HOST: http://localhost:3000
      DATABASE_URL: mongodb://root:password@mongo
      SIGNING_KEY: bsb4q8yiq353lyt7cgcp
      DATABASE_NAME: mygamelist
      WAIT_HOSTS: mongo:27017
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: http://localhost:8000
